repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: double-quote-string-fixer
      - id: check-ast
      - id: check-docstring-first

  - repo: local
    hooks:
      - id: flake8
        name: Flake8
        description: Runs flake8 linting
        entry: pipenv run flake8 --config tox.ini --ignore=E402
        language: system
        types: [python]
      - id: autopep8
        name: PEP 8 Formatting
        description: Formats the code to conform to style guidelines
        entry: pipenv run fix
        language: system
        types: [python]
