
bot-token: ODA4MjgyNzEyMzY3NTYyNzYy.YCER7w.QpW9nM2Uut3QwdBBg4_5bGh3Jvs
mongo-uri: mongodb+srv://admin:hydrogenperoxide_h2o2@smetch.v4eh2.mongodb.net
github-token: 1cec29cb13dbf44f50ea4c2e846f42c7684b7e37
