name: Discord Webhook Update

on:
  push:
    branches:
      - main
      - heroku-deployment
  pull_request:
    branches:
      - main
      - heroku-deployment

jobs:
  Send embed:
  
    runs-on: ubuntu-latest
    name: Send an embed to Discord

    steps:
    - name: Run the GitHub Actions Status Embed Action
      uses: SebastiaanZ/github-status-embed-for-discord@main
      with:
        webhook_id: '808846600653766706'  # Has to be provided as a string
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        pr_author_login: ${{ github.event.pull_request.user.login }}
        pr_number: ${{ github.event.pull_request.number }}
        pr_title: ${{ github.event.pull_request.title }}
        pr_source: ${{ github.event.pull_request.head.label }}
